window.onload = dailyTao;


var chapters = new Array(
  "1. REASON'S REALIZATION: <br>1. The Reason that can be reasoned is not the eternal Reason. The name that can be named is not the eternal Name. The Unnamable is of heaven and earth the beginning. The Namable becomes of the ten thousand things the mother.<br>Therefore it is said: <br>2. 'He who desireless is found <br>The spiritual of the world will sound. <br>But he who by desire is bound <br>Sees the mere shell of things around.' <br>3. These two things are the same in source but different in name. Their sameness is called a mystery. Indeed, it is the mystery of mysteries. Of all spirituality it is the door.", 
  
  "2. SELF-CULTURE:<br>1. Everywhere it is obvious that if beauty makes a display of beauty, it is sheer ugliness. It is obvious that if goodness makes a display of goodness, it is sheer badness. For <br>2. 'To be and not to be are mutually conditioned. The difficult, the easy, are mutually definitioned. The long, the short, are mutually exhibitioned. Above, below, are mutually cognitioned. The sound, the voice, are mutually coalitioned. Before and after are mutually positioned.' <br>3. Therefore <br>The holy man abides by non-assertion in his affairs and conveys by silence his instruction. When the ten thousand things arise, verily, he refuses them not. He quickens but owns not. He acts but claims not. Merit he accomplishes, but he does not dwell on it. <br>'Since he does not dwell on it, it will never leave him.'",
  
  "3. KEEPING THE PEOPLE QUIET:<br>Not exalting worth keeps people from rivalry. Not prizing what is difficult to obtain keeps people from committing theft. Not contemplating what kindles desire keeps the heart unconfused. Therefore the holy man when he governs empties the peoples hearts but fills their souls. He weakens their ambitions but strengthens their backbones. Always he keeps the people unsophisticated and without desire. He causes that the crafty do not dare to act. When he acts with non-assertion there is nothing ungoverned.",
  
  "4. SOURCELESS:<br>Reason is empty, but its use is inexhaustible. In its profundity, verily, it resembleth the father of the ten thousand things.<br>'It will blunt its own sharpness,<br>Will its tangles adjust;<br>It will dim its own radiance<br>And be one with its dust.'<br>Oh, how calm it seems to remain! I know not whose son it is. Before the Lord, Reason takes precedence.",
  
  "5. THE FUNCTION OF EMPTINESS:<br>  Heaven and earth exhibit no benevolence; to them the ten thousand things are like straw dogs. The holy man exhibits no benevolence; to him the hundred families are like straw dogs.<br>  Is not the space between heaven and earth like unto a bellows? It is empty; yet it collapses not. It moves, and more and more comes forth. [But]<br>'How soon exhausted is<br>A gossip's fulsome talk!<br>And should we not prefer<br>On the middle path to walk?'",
  
  "6. THE COMPLETION OF FORM:<br>'The valley spirit not expires,<br>Mysterious mother 'tis called by the sires<br>The mysterious mother's door, to boot,<br>Is called of Heaven and earth the root.<br>Forever and aye it seems to endure<br>And its use is without effort sure.'",
  
  "7. DIMMING RADIANCE:<br>  Heaven endures and earth is lasting. And why can heaven and earth endure and be lasting? Because they do not live for themselves. On that account can they endure.<br>  Therefore the holy man puts his person behind and his person comes to the front. He surrenders his person and his person is preserved. Is it not because he seeks not his own? For that reason he can accomplish his own.",
  
  "8. EASY BY NATURE:<br>  Superior goodness resembleth water. Water in goodness benefiteth the ten thousand things, yet it quarreleth not. Because it dwells in places whice the multitude of men shun, therefore it is near unto the eternal Reason. <br>  For a dwelling goodness chooses the level. For a heart goodness chooses commotion. When giving, goodness chooses benevolence. In words, goodness chooses faith. In government goodness chooses order. In business goodness chooses ability. In its motion goodness chooses timeliness. It quarreleth not. Therefore, it is not rebuked.",
  
  "9. PRACTISING PLACIDITY:<br>  Holding and keeping full, had that not better be left alone? Handling and keeping sharp, can that wear long? If gold and jewels fill the hall no one can protect it.<br>  Rich and high but proud, brings about its own misfortune. To accomplish merit and acquire fame, then to withdraw oneself, that is Heaven's Way.",
  
  "10. WHAT CAN BE DONE:<br>  He who sustains and disciplines his soul and ebraces unity cannot be deranged. Through attention to his vitality and inducing tenderness he can become like a little child. By puriying, by cleansing and profound intuition he can be free from faults.<br>  In loving the people and administering the country he can practise non-assertion. Opening and closing the gates of heaven he can be like a mother-bird: bright, and white, and penetrating the four quarters, he can be unsophisticated. He quickens them and feeds them. He quickens but owns not. He acts but claims not. He excels but rules not. This is called profound virtue.",
  
  "11. THE FUNCTION OF THE NON-EXISTENT:<br>  Thirty spokes unite in one nave on that which is non-existent [on the hole in the nave] depends the wheel's utility. Clay is moulded into a vessel and on that which is non-existent [on its hollowness] depends the vessel's utility. By cutting out doors and windows we buld a house and on that which is non-existent [on the empty space] depends the house's utility.<br> Therefore, when the existence of things is profitable, it is the non-existent in them which renders them useful.",
  
  "12. ABSTAINING FROM DESIRE:<br>'The five colors the human eye will blind,<br>The five notes the human ear wil rend.<br>The five tastes the human mouth offend.'<br><br>'Racing and hunting will human hearts turn mad,<br>Objects of prize make human conduct bad.'<br><br>  Therefore the holy man attends to the inner and not to the outer. He abandons the latter and chooses the former.",
  
  "13. LOATHING SHAME:<br>'Favor and disgrace bode awe.<br>Esteeming the body bodes great trouble.'<br><br>What is meant by 'favor and disgrace bode awe?'<br>Favor humiliates. Its gain bodes awe; its loss bodes awe. This meant by 'favor and disgrace bode awe.'<br>  What is meant by 'Esteeming the body bodes great trouble?'<br>  I have trouble because I have a body. When I have no body, what trouble remains?<br>  Therefore, if one administers the empire as he cares for his body, he can be entrusted with the empire.",
  
  "14. PRAISING THE MYSTERIOUS:<br>  We look at Reason and do not see it; its name is Colorless. We listen to Reason and do not hear it; its name is Soundless. We grope for Reason and do not grasp it; its name is Incorporeal.<br>  These three things cannot futher be analysed. Thus they are combined and conceived as a unity which on its surface is not clear but in its depth not obscure.<br>  Forever and aye Reason remains unnameable, and again and again it returns home to non-existence. This is called the form of the formless, the image of the imageless. This is called transcendentally abstruse.<br>  In front its beginning is not seen. In the rear its end is not seen.<br>  By holding fast to the Reason of the ancients, the present is mastered and the origin of the past understood. This is called Reason's clue.",
  
  "15. THE REVEALERS OF VIRTUE:<br>  Thos of yore who have succeeded in becoming masters are subtile, spiritual, profound, and penetrating. On account of their profundity they cannot be understood. Because they cannot be understood, therefore I endeavor to make them intelligible.<br>  How they are cautious! Like men in winter crossing a river. How reluctant! Like men fearing in the four quarters their neighbors. How rserved! They behave like guests. How elusive! They resemble ice when melting. How simple! They resemble unseasoned wood. How empty! They resemble the valley. How obscure! They resemble troubled waters.<br>  Who by quieting can gradually render muddy waters clear? Who by stirring can gradually quicken the still?<br>  He who keeps this Reason is not anxious to be gilled. Since he is not filled, therefore he can grow old and need not be newly fashioned.",
  
  "16. RETURNING TO THE ROOT:<br>  Attain vacuity's completion and guard ranquility's fulness.<br>  All the ten thousand things arise, and I see them return. Now they bloom in bloom, but each one homeward returneth to its root.<br>  Returning to the root means rest. It signifies the return according to destiny. Return according to destiny means the eternal. Knowing the ternal means enlightenment. Not knowing the eternal causes passions to rise; and that is evil.<br>  Knowing he ternal renders comprehensive. Comprehensive means broad. Broad means royal. Royal means heavenly. Heavenly means Reason. Reason means lasting. Thus the decay of the body implies no danger.",
  
  "17. SIMPLICITY IN HABITS:<br>  Where greate sages are [in power], the subjects do not notice their existence. Where there are lesser sages, the people are attached to them; they praise them. Where still lesser ones are, the people fear them; and where still lesser ones are, the people despise them. For it is If your faith be insufficient, verily, you will receive no faith.'<br>  How reluctantly sages consider their words! Merit they accomplish; deeds they perform; and the hundred families think:' 'We are independent; we are free.'",
  
  "18. THE PALLIATION OF VULGARITY:<br>  When the great Reason is obliterated, we have benevolence and justice. Prudence and circumspection appear, and we have much hypocrisy. When family relations no longer harmonise, we have filial piety and paternal love. When the country and the clans decay through disoder, we have loyalty and allegiance.",
  
  "19. RETURNING TO SIMPLICITY:<br>  Abandon your saintliness; put away your prudence; and the people will gain a hundred-fold!<br>  Abandon your benevolence; put away your justice; and the people will return to filial devotion and paternal love!<br>  Abandon your scheming; put away your gains; and theieves and robbers will no longer exist.<br>  These are the three things for whiche we deem culture insufficient. Therefore it is said:<br>'Hold fast to that whiche will endure,<br>Show theyself simple, preserve thee pure,<br>They own keep small, they desires poor.'",
  
  "20. DIFFERENT FROM THE VULGAR:<br>Abandon learnedness, and you have no vexation. The 'yes' compared with the 'yea,' how little do they differ! But the good compared with the bad, how much do they differ!<br>  What the people dread cannot be dreadless! How great is their desolation. Alas! it has not yet reached its limit.<br>  The multitude of men are happy, so happy, as though celebrating a great feast. They are as though in pringtime ascending a tower. I alone remain quiet, alas! like one that has not yet received an encouraging omen. I am like unto a babe that does not yet smile.<br>  Forlorn am I, O, so forlorn! It appears that I have no place whither I may return home.<br>  The multitude of men all have plenty and I alone appear empty. Alas! I am a man whose heart is foolish.<br>  Ignorant am I, O, so ignorant! Common people are bright, so bright, I alone am dull.<br>  Common people are smart, so smart, I alone am confused, so confused.<br>  Desolate am I, alas! like the sea. Adrift, alas! liek one who has no place where to stay.<br>  The multitude of men all possess usefulness. I alone am awkward and a rustic too. I alone differ from others, but I prize seeking sustenance from our mother."

)

function dailyTao() {
  var randomNum = Math.floor(Math.random() * chapters.length);
  document.getElementById("taoText").innerHTML = chapters[randomNum];
}

