window.onload = dailyTao;


var chapters = new Array(
  "1. REASON'S REALIZATION: <br>1. The Reason that can be reasoned is not the eternal Reason. The name that can be named is not the eternal Name. The Unnamable is of heaven and earth the beginning. The Namable becomes of the ten thousand things the mother.<br>Therefore it is said: <br>2. 'He who desireless is found <br>The spiritual of the world will sound. <br>But he who by desire is bound <br>Sees the mere shell of things around.' <br>3. These two things are the same in source but different in name. Their sameness is called a mystery. Indeed, it is the mystery of mysteries. Of all spirituality it is the door.", 
  
  "2. SELF-CULTURE:<br>1. Everywhere it is obvious that if beauty makes a display of beauty, it is sheer ugliness. It is obvious that if goodness makes a display of goodness, it is sheer badness. For <br>2. 'To be and not to be are mutually conditioned. <br>The difficult, the easy, are mutually definitioned. <br>The long, the short, are mutually exhibitioned. <br>Above, below, are mutually cognitioned. <br>The sound, the voice, are mutually coalitioned. <br>Before and after are mutually positioned.' <br>3. Therefore <br>The holy man abides by non-assertion in his affairs and conveys by silence his instruction. When the ten thousand things arise, verily, he refuses them not. He quickens but owns not. He acts but claims not. Merit he accomplishes, but he does not dwell on it. <br>'Since he does not dwell on it, it will never leave him.'",
  
  "3. KEEPING THE PEOPLE QUIET:<br>Not exalting worth keeps people from rivalry. Not prizing what is difficult to obtain keeps people from committing theft. Not contemplating what kindles desire keeps the heart unconfused. Therefore the holy man when he governs empties the peoples' hearts but fills their souls. He weakens their ambitions but strengthens their backbones. Always he keeps the people unsophisticated and without desire. He causes that the crafty do not dare to act. When he acts with non-assertion there is nothing ungoverned.",
  
  "4. SOURCELESS:<br>Reason is empty, but its use is inexhaustible. In its profundity, verily, it resembleth the father of the ten thousand things.<br>'It will blunt its own sharpness,<br>Will its tangles adjust;<br>It will dim its own radiance<br>And be one with its dust.'<br>Oh, how calm it seems to remain! I know not whose son it is. Before the Lord, Reason takes precedence.",
  
  "5. THE FUNCTION OF EMPTINESS:<br>  Heaven and earth exhibit no benevolence; to them the ten thousand things are like straw dogs. The holy man exhibits no benevolence; to him the hundred families are like straw dogs.<br>  Is not the space between heaven and earth like unto a bellows? It is empty; yet it collapses not. It moves, and more and more comes forth. [But]<br>'How soon exhausted is<br>A gossip's fulsome talk!<br>And should we not prefer<br>On the middle path to walk?'",
  
  "6. THE COMPLETION OF FORM:<br>'The valley spirit not expires,<br>Mysterious mother 'tis called by the sires<br>The mysterious mother's door, to boot,<br>Is called of Heaven and earth the root.<br>Forever and aye it seems to endure<br>And its use is without effort sure.'",
  
  "7. DIMMING RADIANCE:<br>  Heaven endures and earth is lasting. And why can heaven and earth endure and be lasting? Because they do not live for themselves. On that account can they endure.  Therefore the holy man puts his person behind and his person comes to the front. He surrenders his person and his person is preserved. Is it not because he seeks not his own? For that reason he can accomplish his own.",
  
  "8. EASY BY NATURE:<br>  Superior goodness resembleth water. Water in goodness benefiteth the ten thousand things, yet it quarreleth not. Because it dwells in places which the multitude of men shun, therefore it is near unto the eternal Reason.   For a dwelling, goodness chooses the level. For a heart, goodness chooses commotion. When giving, goodness chooses benevolence. In words, goodness chooses faith. In government goodness chooses order. In business goodness chooses ability. In its motion goodness chooses timeliness. It quarreleth not. Therefore, it is not rebuked.",
  
  "9. PRACTISING PLACIDITY:<br>  Holding and keeping full, had that not better be left alone? Handling and keeping sharp, can that wear long? If gold and jewels fill the hall, no one can protect it.  Rich and high but proud, brings about its own misfortune. To accomplish merit and acquire fame, then to withdraw oneself, that is Heaven's Way.",
  
  "10. WHAT CAN BE DONE:<br>  He who sustains and disciplines his soul and embraces unity cannot be deranged. Through attention to his vitality and inducing tenderness he can become like a little child. By purifying, by cleansing and profound intuition he can be free from faults.  In loving the people and administering the country he can practise non-assertion. Opening and closing the gates of heaven he can be like a mother-bird: <br>bright, and white, and penetrating the four quarters, he can be unsophisticated. He quickens them and feeds them. He quickens but owns not. He acts but claims not. He excels but rules not. This is called profound virtue.",
  
  "11. THE FUNCTION OF THE NON-EXISTENT:<br>  Thirty spokes unite in one nave on that which is non-existent [on the hole in the nave] depends the wheel's utility. Clay is moulded into a vessel and on that which is non-existent [on its hollowness] depends the vessel's utility. By cutting out doors and windows we build a house and on that which is non-existent [on the empty space] depends the house's utility.<br> Therefore, when the existence of things is profitable, it is the non-existent in them which renders them useful.",
  
  "12. ABSTAINING FROM DESIRE:<br>'The five colors the human eye will blind,<br>The five notes the human ear will rend.<br>The five tastes the human mouth offend.'<br><br>'Racing and hunting will human hearts turn mad,<br>Objects of prize make human conduct bad.'<br><br>  Therefore the holy man attends to the inner and not to the outer. <br>He abandons the latter and chooses the former.",
  
  "13. LOATHING SHAME:<br>'Favor and disgrace bode awe.<br>Esteeming the body bodes great trouble.'<br><br>What is meant by 'favor and disgrace bode awe?'<br>Favor humiliates. Its gain bodes awe; its loss bodes awe. This meant by 'favor and disgrace bode awe.'<br>  What is meant by 'Esteeming the body bodes great trouble?'<br>  I have trouble because I have a body. When I have no body, what trouble remains?<br>  Therefore, if one administers the empire as he cares for his body, he can be entrusted with the empire.",
  
  "14. PRAISING THE MYSTERIOUS:<br>  We look at Reason and do not see it; its name is Colorless. We listen to Reason and do not hear it; its name is Soundless. We grope for Reason and do not grasp it; its name is Incorporeal.  These three things cannot futher be analysed. Thus they are combined and conceived as a unity which on its surface is not clear but in its depth not obscure.  Forever and aye Reason remains unnameable, and again and again it returns home to non-existence. This is called the form of the formless, the image of the imageless. This is called transcendentally abstruse.  In front its beginning is not seen. In the rear its end is not seen.  By holding fast to the Reason of the ancients, the present is mastered and the origin of the past understood. This is called Reason's clue.",
  
  "15. THE REVEALERS OF VIRTUE:<br>  Those of yore who have succeeded in becoming masters are subtile, spiritual, profound, and penetrating. On account of their profundity they cannot be understood. Because they cannot be understood, therefore I endeavor to make them intelligible.  How they are cautious! Like men in winter crossing a river. How reluctant! Like men fearing in the four quarters their neighbors. How reserved! They behave like guests. How elusive! They resemble ice when melting. How simple! They resemble unseasoned wood. How empty! They resemble the valley. How obscure! They resemble troubled waters.  Who by quieting can gradually render muddy waters clear? Who by stirring can gradually quicken the still?  He who keeps this Reason is not anxious to be gilled. Since he is not filled, therefore he can grow old and need not be newly fashioned.",
  
  "16. RETURNING TO THE ROOT:<br>  Attain vacuity's completion and guard tranquility's fullness.<br>  All the ten thousand things arise, and I see them return. Now they bloom in bloom, but each one homeward returneth to its root.  Returning to the root means rest. It signifies the return according to destiny. Return according to destiny means the eternal. Knowing the eternal means enlightenment. Not knowing the eternal causes passions to rise; and that is evil.  Knowing he eternal renders comprehensive. Comprehensive means broad. Broad means royal. Royal means heavenly. Heavenly means Reason. Reason means lasting. Thus the decay of the body implies no danger.",
  
  "17. SIMPLICITY IN HABITS:<br>  Where great sages are [in power], the subjects do not notice their existence. Where there are lesser sages, the people are attached to them; they praise them. Where still lesser ones are, the people fear them; and where still lesser ones are, the people despise them. For it is If your faith be insufficient, verily, you will receive no faith.'<br>  How reluctantly sages consider their words! <br>Merit they accomplish; deeds they perform; and the hundred families think:' <br>'We are independent; we are free.'",
  
  "18. THE PALLIATION OF VULGARITY:<br>  When the great Reason is obliterated, we have benevolence and justice. Prudence and circumspection appear, and we have much hypocrisy. When family relations no longer harmonise, we have filial piety and paternal love. When the country and the clans decay through disorder, we have loyalty and allegiance.",
  
  "19. RETURNING TO SIMPLICITY:<br>  Abandon your saintliness; put away your prudence; and the people will gain a hundred-fold!  Abandon your benevolence; put away your justice; and the people will return to filial devotion and paternal love!  Abandon your scheming; put away your gains; and theieves and robbers will no longer exist.  These are the three things for whiche we deem culture insufficient. Therefore it is said:<br>'Hold fast to that whiche will endure,<br>Show thyself simple, preserve thee pure,<br>They own keep small, they desires poor.'",
  
  "20. DIFFERENT FROM THE VULGAR:<br>Abandon learnedness, and you have no vexation. The 'yes' compared with the 'yea,' how little do they differ! But the good compared with the bad, how much do they differ!  What the people dread cannot be dreadless! How great is their desolation. Alas! it has not yet reached its limit.  The multitude of men are happy, so happy, as though celebrating a great feast. They are as though in Springtime ascending a tower. I alone remain quiet, alas! like one that has not yet received an encouraging omen. I am like unto a babe that does not yet smile.  Forlorn am I, O, so forlorn! It appears that I have no place whither I may return home.  The multitude of men all have plenty and I alone appear empty. Alas! I am a man whose heart is foolish.  Ignorant am I, O, so ignorant! Common people are bright, so bright, I alone am dull.  Common people are smart, so smart, I alone am confused, so confused.  Desolate am I, alas! like the sea. Adrift, alas! like one who has no place where to stay.  The multitude of men all possess usefulness. I alone am awkward and a rustic too. I alone differ from others, but I prize seeking sustenance from our mother.",
  
  "21. EMPTYING THE HEART:<br>'Vast virtue's form<br>Follows Reason's norm.<br>And Reason's nature<br>Is vague and eluding.<br>How eluding and vague<br>All types including.<br>How vague and eluding!<br>All beings including,<br>How deep, and how obscure.<br>It harbors the spirit pure,<br>Whose truth is ever sure,<br>Whose faith abides for aye<br>From of yore until to-day.<br>Its name is without cessation.<br>It watches the world's formation.'<br>  Whereby do I know that it watches the world's formation? By this same Reason!",
  
  "22. HUMILITY'S INCREASE:<br>'The deficient will recuperate.<br>And the crooked shall be straight.<br>The empty find their fill.<br>The worn with strength will thrill.<br>Who have little shall receive.<br>Who have much will have to grieve.'<br>  Therefore the holy man embraces unity and becomes for all the world a model. He is not self-displaying, and thus he shines. He is not self-approving, and thus he is distinguished. He is not self-praising, and thus he acquires merit. He is not self-glorifying and thus he excels. Since he does not quarrel, therefore no one in the world can quarrel with him.   The saying of the ancients: 'The deficient will recuperate,' is it in any way vainly spoken? Verily, they will recuperate and return home.",
  
  "23. EMPTINESS AND NON-EXISTENCE:<br>  To be taciturn is the natural way.<br>  A hurricane does not outlast the morning. A cloudburst does not outlast the day. Who causes these events but heaven and earth? If even heaven and earth canot be unremitting, will not man be much less so?<br>  Therefore one who pursues his business with Reason, the man of Reason, is identified with Reason. The man who pursues his business with virtue is identified with virtue. The man who pursues his business with loss is identified with loss. When identified with Reason, he forsooth joyfully embraces Reason; when identified with virtue, he forsooth joyfully embraces virtue; and when identified with loss, he forsooth joyfully embraces loss.<br>'He whose faith is insufficient shall not find faith.'",
  
  "24. TROUBLES IN [THE EAGERNESS TO ACQUIRE] MERIT:<br>  A man on tiptoe cannot stand. A man astride cannot walk. A self-displaying man cannot shine. A self-approving man cannot be distinguished. A self-praising man cannot acquire merit. A self-glorying man cannot excel. Before the tribunal of Reason he is like offal of food and like an excrescence in the system which all people are likely to detest. Therefore, one who has Reason does not rely on him.",
  
  "25. IMAGING THE MYSTERIOUS:<br>  There is Being that is all-containing, which precedes the existence of heaven and earth. How calm it is! How incorporeal! Alone it stands and does not change. Everywhere it goes without running a risk, and can on that account become the world's mother. I know not its name. Its character is defined as Reason. When obliged to give it a name, I call it the Great. The Great I call the Evasive. The Evasive I call the Distant. The Distant I call the Returning.<br>  The saying goes: 'Reason is great, Heaven is great, Earth is great, and Royalty also is great. There are four things in the world that are great, and Royalty is one of them'<br>  Man's standard is the Earth. The earth's standard is Heaven. Heaven's standard is Reason. Reason's standard is intrinsic.",
  
  "26. THE VIRTUE OF DIGNITY:<br>  The heavy is of the light the root, and rest is motion's master.  Therefore the holy man in his daily walk does not depart from dignity. Although he may have magnificent sights, he calmy sits with liberated mind. <br>  But how is it with the master of the ten thousand chariots? In his personal conduct he makes light of the empire. He makes light of it and will lose his vassals. He is passionate and will lose the throne.",
  
  "27. THE FUNCTION OF SKILL:<br>'Good travellers leave not trace nor track,<br>Good speakers, in logic sow no lack,<br>Good counters need no counting rack.<br><br>'Good lockers bolting bars need not, <br>Yet none their locks can loose.<br>Good binders need not string nor knot,<br>Yet none unties their noose.'<br>Therefore the holy man is always a good saviour of men, for there are no outcast people. He is always a good saviour of things, for there are no outcast things. This is called concealed enlightenment.<br>  Therefore the good man is the bad man's instructor, while the bad man is the good man's capital. He who does not esteem his instructor, and he who does not love his capital, although he maybe prudent, is greatly disconcerted. This I call significant spirituality.",
  
  "28. RETURNING TO SIMPLICITY:<br> 'Who his manhood shows<br>And his womanhood knows<br>Becomes the empire's river.<br>Is he the empire's river,<br>He will from virtue never deviate,<br>And home he turneth to a child's estate.<br><br>'Who his brightness shows<br>And his blackness knows<br>Becomes the empire's model.<br>Is he the empire's model,<br>Of virtue never he'll be destitute,<br>And home he turneth to the absolute.<br><br>'Who knows his fame<br>And guards his shame<br>Becomes the empire's valley.<br>Is he the empire's valley,<br>For e'er his virtue will sufficient be, <br>And home he turneth to simplicity.'<br>  By scattering about his simplicity he makes[of the people] vessels of usefulness. The holy man employs them as officers; for a great administration does no harm.",
  
  "29. NON-ASSERTION:<br>  When one desires to take in hand the empire and make it, I see him not succeed. The empire is a divine vessel which cannot be made. One who makes it, mars it. One who takes it, loses it. And it is said of beings:<br>'Some are obsequious, others move boldly,<br>Some breathe warmly, others coldly,<br>Some are strong and others weak,<br>Some rise proudly, others sneak.'<br>  Therefore the holy man abandons pleasure, he abandons extravagance, he abandons indulgence.",
  
  "30. BE CHARY OF WAR:<br>  He who with Reason assists the master of mankind will not with arms conquer the empire. His methods [are such as] invite requital.<br>  Where armies are quartered briars and thorns grow. Great wars unfailingly are followed by famines. A good man acts resolutely and then stops. He ventures not to take by force. He is resolute but not boastful; resolute bot not haughty; resolute by not arrogant; resolute because he cannot avoid it; resolute but not violent.<br>  Things thrive and then grow old. This is called un-Reason. Un-Reason soon ceases."

)

function dailyTao() {
  var randomNum = Math.floor(Math.random() * chapters.length);
  document.getElementById("taoText").innerHTML = chapters[randomNum];
}


